### ISSUE TITLE
"Failed to analyze metadata" with typed keys

### ISSUE THREAD

**Issue by starsolaris** [miyaji255/hono-typia-openapi#2]
```ts
type UUID = string & typia.tags.Format<"uuid">;
type Context = {
  [prop: UUID]: {}
};
const app = new Hono()
  .get("/some", async function context(c) {
      return c.json(
        {} as Context
      );
  });
```
will produce
```sh
Error: Failed to analyze metadata
    at createOpenAPISchema (/home/star/docker/1.3.10/images/service/authz-decision/node/node_modules/hono-typia-openapi/dist/cjs/core/createOpenAPISchema.js:18:15)
    at analyzeSchema (/home/star/docker/1.3.10/images/service/authz-decision/node/node_modules/hono-typia-openapi/dist/cjs/core/index.js:83:66)
    at generateOpenAPIDocs (/home/star/docker/1.3.10/images/service/authz-decision/node/node_modules/hono-typia-openapi/dist/cjs/core/index.js:53:12)
    at main (/home/star/docker/1.3.10/images/service/authz-decision/node/node_modules/hono-typia-openapi/dist/cjs/cli.js:153:56)
```

But if change UUID to ```type UUID = string;``` then it will work

**Comment by miyaji255** [comment]
Thanks for the bug report.
That is a problem due to typia not being able to parse it.
